name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ] 

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: yawn-linux
          - os: windows-2025-vs2026
            artifact_name: yawn-windows.exe
          - os: macos-15
            artifact_name: yawn-macos

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Linux Deps
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - name: Build
        run: odin build . -out:${{ matrix.artifact_name }} -o:speed

      - name: Upload for Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}

  release:
    needs: build 
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./binaries
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./binaries/*
          generate_release_notes: true 
          draft: false
          prerelease: false
